MultiIndex series and datafrmae

In [4]:
import numpy as np 
import pandas as pd

In [5]:
#multi index series (problems)(this is not ideal approch to create multi index series)
index_val=[('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a=pd.Series([1,2,3,4,5,6,7,8,],index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [6]:
# Hierarical Indexing  (best approchs)
#how to create proper multi index level with in single index 
# pd.MultiIndex.from_tuples()
index_val=[('cse',2019),('cse',2020),('cse',2021),('ece',2022),('ece',2023),('ece',2024)]
multiIndex=pd.MultiIndex.from_tuples(index_val)
multiIndex #multi index object 
multiIndex.levels[0]
multiIndex.levels[1]

Index([2019, 2020, 2021, 2022, 2023, 2024], dtype='int64')

In [7]:
#pd.multiIndex.from_product()
multiIndex_pro=pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])
multiIndex_pro

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [8]:
#creating series with multiindex object 
s=pd.Series([1,2,3,4,5,6,7,8],index=multiIndex)
s #2D dimenstions

ValueError: Length of values (8) does not match length of index (6)

In [ ]:
#how to fetch  from series 
s['cse']
s.shape

(8,)

In [ ]:
# unstack (this function help to convert multiindex into dataframe )
temp=s.unstack()
temp

#stack (back to multiindex)
temp.stack()

temp

In [ ]:
# why we use multiindex series ?
# higer dimenstion object represent in series and dataframe

In [ ]:
# multiindex dataframe

branch_df = pd.DataFrame(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [9, 10],
        [11, 12],
        [13, 14],
        [15, 16]
    ],
    index=multiIndex,
    columns=['avg_package', 'student']
    )

branch_df

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [ ]:
branch_df['avg_package']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [ ]:
#multiindex df from colns perspective 
branch_df2=pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0]
    ],
    index=[2019,2020,2021,2022],
    columns=pd.MultiIndex.from_product([['Delhi','mumbai'],['avg_package','student']])

)

branch_df2.mumbai.student

2019    0
2020    0
2021    0
2022    0
Name: student, dtype: int64

In [ ]:
branch_df3=pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0]
    ],
    index=multiIndex,
    columns=pd.MultiIndex.from_product([['Delhi','mumbai'],['avg_package','student']])

)

branch_df3.Delhi.student.cse[2020]

#we need to use multiindex becouse we can convert any higer order dimenstions in lower dimenstions like series and datframe

np.int64(4)

In [ ]:
#stacking and unstacking 
temp=branch_df.unstack().stack().stack()
temp

branch_df2.stack().stack()

branch_df3.unstack().unstack()
branch_df3.stack().stack()

#unstacking rows convert into colns
#stackign columns convert into rows

cse  2019  avg_package  Delhi      1
                        mumbai     0
           student      Delhi      2
                        mumbai     0
     2020  avg_package  Delhi      3
                        mumbai     0
           student      Delhi      4
                        mumbai     0
     2021  avg_package  Delhi      5
                        mumbai     0
           student      Delhi      6
                        mumbai     0
     2022  avg_package  Delhi      7
                        mumbai     0
           student      Delhi      8
                        mumbai     0
ece  2019  avg_package  Delhi      9
                        mumbai     0
           student      Delhi     10
                        mumbai     0
     2020  avg_package  Delhi     11
                        mumbai     0
           student      Delhi     12
                        mumbai     0
     2021  avg_package  Delhi     13
                        mumbai     0
           student      Delhi     14
                        mumbai     0
     2022  avg_package  Delhi     15
                        mumbai     0
           student      Delhi     16
                        mumbai     0
dtype: int64

In [ ]:
#working with multi index dataframe

branch_df3  #4d example 
branch_df3.head()
branch_df3.shape
branch_df3.info()
branch_df3.describe()
branch_df3.sum()
branch_df3.count()

branch_df3.isnull()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Delhi, avg_package)   8 non-null      int64
 1   (Delhi, student)       8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, student)      8 non-null      int64
dtypes: int64(4)
memory usage: 632.0+ bytes

               Delhi              mumbai
         avg_package student avg_package student
cse 2019       False   False       False   False
    2020       False   False       False   False
    2021       False   False       False   False
    2022       False   False       False   False
ece 2019       False   False       False   False
    2020       False   False       False   False
    2021       False   False       False   False
    2022       False   False       False   False

In [ ]:
#Extracting rows 
branch_df3
branch_df3.loc[('cse',2019)]
branch_df3.loc[('ece',2019)]
branch_df3.loc[('cse',2020):('ece',2022):2]

#using iloc
branch_df3[0:6:2]

               Delhi              mumbai
         avg_package student avg_package student
cse 2019           1       2           0       0
    2021           5       6           0       0
ece 2019           9      10           0       0

In [ ]:
# extarcting columns
branch_df3['Delhi']['student']

# multi columns 
branch_df3.iloc[:,1:3]

           Delhi      mumbai
         student avg_package
cse 2019       2           0
    2020       4           0
    2021       6           0
    2022       8           0
ece 2019      10           0
    2020      12           0
    2021      14           0
    2022      16           0

In [ ]:
#extractign boths 
branch_df3.iloc[[0,4],[1,2]]

           Delhi      mumbai
         student avg_package
cse 2019       2           0
ece 2019      10           0

In [ ]:
# sorting on multiIndex
branch_df3.sort_index(ascending=False)
branch_df3.sort_index(ascending=[False,True ])

               Delhi              mumbai
         avg_package student avg_package student
ece 2019           9      10           0       0
    2020          11      12           0       0
    2021          13      14           0       0
    2022          15      16           0       0
cse 2019           1       2           0       0
    2020           3       4           0       0
    2021           5       6           0       0
    2022           7       8           0       0

In [ ]:
#transpose
branch_df3.transpose()

#swaplevel
branch_df3.swaplevel(axis=1)

         avg_package student avg_package student
               Delhi   Delhi      mumbai  mumbai
cse 2019           1       2           0       0
    2020           3       4           0       0
    2021           5       6           0       0
    2022           7       8           0       0
ece 2019           9      10           0       0
    2020          11      12           0       0
    2021          13      14           0       0
    2022          15      16           0       0

In [ ]:
#long vs wide data formate 

#melt -> wide data formate convert into long data fromate 

pd.DataFrame({'cse':[102]}).melt()

pd.DataFrame({'cse':[102],'ece':[102]}).melt()






#pivet -> long formate convert wide data fromate

  variable  value
0      cse    102
1      ece    102

Pivot table

In [ ]:
import seaborn as sns

In [ ]:
df=sns.load_dataset('tips')
new =df.groupby('sex')
new.total_bill.mean() 


df.groupby(['sex','smoker'])['total_bill'].mean().unstack()

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
#using pviat table 
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='count')

#all colns togeather
df.pivot_table(index='sex',columns='smoker',aggfunc='mean',numeric_only=True)

            size                 tip           total_bill
smoker       Yes        No       Yes        No        Yes         No
sex
Male    2.500000  2.711340  3.051167  3.113402  22.284500  19.791237
Female  2.242424  2.592593  2.931515  2.773519  17.977879  18.105185

In [ ]:
#multidimentional 
df.pivot_table(index=['sex','smoker'],columns=['day','time'],values='total_bill')

day                 Thur               Fri                Sat        Sun
time               Lunch Dinner      Lunch  Dinner     Dinner     Dinner
sex    smoker
Male   Yes     19.171000    NaN  11.386667  25.892  21.837778  26.141333
       No      18.486500    NaN        NaN  17.475  19.929063  20.403256
Female Yes     19.218571    NaN  13.260000  12.200  20.266667  16.540000
       No      15.899167  18.78  15.980000  22.750  19.003846  20.824286

In [ ]:
#margins
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='mean', margins=True)

smoker        Yes         No        All
sex
Male    22.284500  19.791237  20.744076
Female  17.977879  18.105185  18.056897
All     20.756344  19.188278  19.785943

In [ ]:
#ploting graph
expenses=pd.read_csv(r'C:\Users\hp\Python-Fundamentals-\Pandas\expense_data.csv')
expenses

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,3/1/2022 18:56,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,3/1/2022 18:22,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0
...,...,...,...,...,...,...,...,...,...,...,...
272,11/22/2021 14:16,CUB - online payment,Food,NaN,Dinner,90.0,Expense,NaN,90.0,INR,90.0
273,11/22/2021 14:16,CUB - online payment,Food,NaN,Lunch with company,97.0,Expense,NaN,97.0,INR,97.0
274,11/21/2021 17:07,CUB - online payment,Transportation,NaN,Rapido,130.0,Expense,NaN,130.0,INR,130.0
275,11/21/2021 15:50,CUB - online payment,Food,NaN,Lunch,875.0,Expense,NaN,875.0,INR,875.0
276,11/21/2021 13:30,CUB - online payment,Other,NaN,Got from gobi,2000.0,Income,NaN,2000.0,INR,2000.0

Vectorized strings operations

In [ ]:
#what is vectorized operations 
a=np.array([1,2,3,4])

array([1, 0, 1, 0])

In [ ]:
# python vectorize operation is not effiecent becz  it not perform operation on missing values it throw error 
#pandas vectorize the fast and efficent for larger data sets

In [ ]:
s=pd.Series(['cat','mat',None])
s.str.startswith('c')

0     True
1    False
2    False
dtype: bool

In [10]:
#import csv file 
titanic=pd.read_csv(r'C:\Users\hp\Python-Fundamentals-\Pandas\titanic.csv')
titanic['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [11]:
# comman function
titanic['Name'].str.upper()
titanic['Name'].str.capitalize()
titanic['Name'].str.len().max()
titanic['Name'][titanic['Name'].str.len()==82]
titanic['Name'].str.strip() #leading and tailing space remove karna hai

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [12]:
# split -> get 
#fetching lastname 
titanic['LastName']=titanic['Name'].str.split(',').str.get(0)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,LastName
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Graham
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Johnston
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Dooley

In [35]:
#make new columns for name 
titanic[['tittle','firstname']]=titanic['Name'].str.split(',').str.get(1).str.strip().str.split(' ',n=1,expand=True)

titanic['tittle'].value_counts()

tittle
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Mlle.          2
Col.           2
Don.           1
Mme.           1
Ms.            1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
#replace 
titanic['tittle']=titanic['tittle'].str.replace('Ms.','Miss.')
titanic['tittle'].value_counts()

tittle
Mr.          517
Miss.        183
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Mlle.          2
Col.           2
Don.           1
Mme.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
#filtering 
#passangers name  startswith ('a')\endswith('A')
titanic[titanic['firstname'].str.startswith('A')]
titanic[titanic['firstname'].str.endswith('A')]

#isdigit
titanic[titanic['firstname'].str.isdigit()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, LastName, tittle, firstname]
Index: []

In [ ]:
#applying regular expressions (complex pattern fro searching )

titanic[titanic['firstname'].str.contains('john',case=False)]

#firstname end /start with aeiou
titanic[titanic['firstname'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,LastName,tittle,firstname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Johnson,Mrs.,Oscar W (Elisabeth Vilhelmina Berg)
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Bonnell,Miss.,Elizabeth
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,Andersson,Mr.,Anders Johan
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,McGowan,Miss.,"Anna ""Annie"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,NaN,S,Abbing,Mr.,Anthony
854,855,0,2,"Carter, Mrs. Ernest Courtenay (Lilian Hughes)",female,44.0,1,0,244252,26.0000,NaN,S,Carter,Mrs.,Ernest Courtenay (Lilian Hughes)
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C,Duran y More,Miss.,Asuncion
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,Najib,Miss.,"Adele Kiamie ""Jane"""
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S,Gustafsson,Mr.,Alfred Ossian

In [57]:
#slicing 
titanic['Name'].str[::-1]
titanic['Name'].str[::2]
titanic['Name'].str[:4:2]

0      Ba
1      Cm
2      Hi
3      Ft
4      Al
       ..
886    Mn
887    Ga
888    Jh
889    Bh
890    Do
Name: Name, Length: 891, dtype: str

PANDAS DATE AND TIME