In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

hello worlds

LEARNING PANDAS DATAFRAME

In [45]:
# tabular data  is dataframe (2d staructre data consistent rows and columns )
# each rows / colums  are series 

#data frame using list(2d list )

student_data=[
    [100,80,40],
    [34,60,21],
    [50,50,50]    
]
student = pd.DataFrame(student_data,columns=['iq','marks','package'])

In [5]:
#data frame using dictionaries 
student_dict={
    'Iq':[100,60,40],
    'marks':[90,70,32],
    'package':[100,70,60]
}
pd.DataFrame(student_dict)

    Iq  marks  package
0  100     90      100
1   60     70       70
2   40     32       60

In [184]:
#using read csv 
movie=pd.read_csv(r'C:\Users\hp\Python fundamentals\Pandas\movies.csv')
Ipl_match=pd.read_csv(r'C:\Users\hp\Python fundamentals\Pandas\ipl-matches.csv')
movie
Ipl_match

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [ ]:
movie.columns
Ipl_match.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str')

In [25]:
# DataFrame attributes and methods 

#shape 
movie.shape
Ipl_match.shape

#dtype(each columns datatype )
movie.dtypes

#Index 
movie.index

#question attributes vs methods 

# coulmns
movie.columns

#values
Ipl_match.values #2d numpy array 

#head
movie.head(2) 
# tail
movie.tail(2)

#shample (randomly rows )
Ipl_match.sample

<bound method NDFrame.sample of           ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2
2    1312198     Kolkata  2022-05-25     2022   Eliminator
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1
4    1304116      Mumbai  2022-05-22     2022           70
..       ...         ...         ...      ...          ...
945   335986     Kolkata  2008-04-20  2007/08            4
946   335985      Mumbai  2008-04-20  2007/08            5
947   335984       Delhi  2008-04-19  2007/08            3
948   335983  Chandigarh  2008-04-19  2007/08            2
949   335982   Bangalore  2008-04-18  2007/08            1

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans
1    Royal Challengers Bangalore             Rajasthan Royals
2    Royal Challengers Bangalore         Lucknow Super Giants
3               Rajasthan Royals               Gujarat Titans
4            Sunrisers Hyderabad                 Punjab Kings
..                           ...                          ...
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
2                         Eden Gardens, Kolkata         Lucknow Super Giants
3                         Eden Gardens, Kolkata               Gujarat Titans
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad
..                                          ...                          ...
945                                Eden Gardens              Deccan Chargers
946                            Wankhede Stadium               Mumbai Indians
947                            Feroz Shah Kotla             Rajasthan Royals
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0
1          field         N             Rajasthan Royals  Wickets     7.0
2          field         N  Royal Challengers Bangalore     Runs    14.0
3          field         N               Gujarat Titans  Wickets     7.0
4            bat         N                 Punjab Kings  Wickets     5.0
..           ...       ...                          ...      ...     ...
945          bat         N        Kolkata Knight Riders  Wickets     5.0
946          bat         N  Royal Challengers Bangalore  Wickets     5.0
947          bat         N             Delhi Daredevils  Wickets     9.0
948          bat         N          Chennai Super Kings     Runs    33.0
949        field         N        Kolkata Knight Riders     Runs   140.0

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...
..     ...             ...                                                ...
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...
946    NaN      MV Boucher  ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...
947    NaN     MF Maharoof  ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...
948    NaN      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949    NaN     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players        Umpire1  \
0    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1    ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2    ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4    ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary
..                                                 ...            ...
945  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...      BF Bowden
946  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...       SJ Davis
947  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...      Aleem Dar
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...      MR Benson
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...      Asad Rauf

            Umpire2
0       Nitin Menon
1       Nitin Menon
2          MA Gough
3         VK Sharma
4     NA Patwardhan
..              ...
945     K Hariharan
946       DJ Harper
947  GA Pratapkumar
948      SL Shastri
949     RE Koertzen

[950 rows x 20 columns]>

In [27]:
movie.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB

In [28]:
Ipl_match.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

In [ ]:
#describe   only numerical values apply 
movie.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [ ]:
#isnull((colums missing value ))
Ipl_match.isnull().sum()
movie.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [36]:
#dublicate 
movie.duplicated()  #true =dublicated  and false =not dublicated 
movie.duplicated().sum()

np.int64(0)

In [ ]:
#rename (replace columns name ),inplace is used to make chnages in original arrray
    
student.rename(columns={'package':'LPA'},inplace=True)
student

    iq  marks  LPA
0  100     80   40
1   34     60   21
2   50     50   50

In [57]:
#math Methods 
movie.sum(axis=0)

movie.mean(numeric_only=True)

is_adult              0.000000
year_of_release    2010.263966
imdb_rating           5.557459
imdb_votes         5384.263352
dtype: float64

In [65]:
#selcting colns 

#fetching single coln
movie['title_x']

Ipl_match['Venue']

#fetching multiple colns 

movie.columns

type(movie[['title_x', 'imdb_id', 'poster_path']])

pandas.DataFrame

In [ ]:
#Selecting rows 

#iloc (searches using index postion(absolute 0,1,2,3,4.......... ) )
movie.iloc[0:5] #last postion is excluded 

movie.iloc[[0,3,4,5]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

In [72]:
# #loc (indexing throw labels ) you need to provide labels 
# movie.loc['key name '] and last postion is  included

In [ ]:
#fetching rows and colns
    
movie.iloc[0:3,0:3]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [ ]:
#filtering data 
Ipl_match.head(2)

#find all final winers 
Ipl_match.columns
new_df=Ipl_match[Ipl_match['MatchNumber']=='Final']
new_df[['Season','WinningTeam']]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [131]:
#find out how many super over is occured 
Ipl_match[Ipl_match['SuperOver'] =='Y'].shape[0]

14

In [157]:
#how many match csk win in kolkata 
# & use with binary 
Ipl_match[(Ipl_match['City']=='Kolkata')&(Ipl_match['WinningTeam']=='Chennai Super Kings')].shape[0]

# Ipl_match[Ipl_match['Venue']=='Eden Gardens']

5

#toss winner is match winner  in percentage 
(Ipl_match[Ipl_match['TossWinner'] == Ipl_match['WinningTeam']].shape[0]/Ipl_match.shape[0])*100

In [169]:
# imbd_rating higer then 8 and voters >10000
movie[(movie['imdb_rating'] >8) &(movie['imdb_votes']>10000)].shape[0]

43

In [173]:
movie[movie['genres']=='Action']

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
78,Dabangg 3,tt7059844,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dabangg_3,Dabangg 3,Dabangg 3,0,2019,160,Action,3.0,15000,Third installment of the Dabanng film series.,Third installment of the Dabanng film series.,NaN,Salman Khan|Sonakshi Sinha|Sudeep|Mahesh Manjr...,NaN,NaN
176,Aa Gaya Hero,tt5896934,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aa_Gaya_Hero,Aa Gaya Hero,Aa Gaya Hero,0,2017,123,Action,2.9,304,ACP Ravindra Varma a fearless and sincere pol...,ACP Ravindra Varma a fearless and sincere pol...,File of Abhinay Chakra.,Govinda|Richa Sharma|Poonam Pandey|Sweta Sharm...,NaN,16 March 2017 (India)
367,Gabbar Is Back,tt2424988,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gabbar_Is_Back,Gabbar is Back,Gabbar is Back,0,2015,128,Action,7.1,21430,Gabbar Singh Rajput (Akshay Kumar) creates his...,A grief-stricken man takes the law into his ow...,NaN,Akshay Kumar|Shruti Haasan|Kareena Kapoor|Jaid...,1 win,1 May 2015 (India)
368,Gabbar Is Back,tt2424988,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gabbar_is_Back,Gabbar is Back,Gabbar is Back,0,2015,128,Action,7.1,21430,Gabbar Singh Rajput (Akshay Kumar) creates his...,A grief-stricken man takes the law into his ow...,NaN,Akshay Kumar|Shruti Haasan|Kareena Kapoor|Jaid...,1 win,1 May 2015 (India)
435,Sorry Daddy,tt4994210,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sorry_Daddy_(film),Sorry Daddy,Sorry Daddy,0,2015,\N,Action,5.4,5,Inspector Ravi Sharma (Shamim Khan) is very ho...,Sorry daddy is a Children story centring aroun...,NaN,Shamim Khan|Mukesh Tiwari|,NaN,NaN
452,Ranbanka,tt5151622,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ranbanka,Ranbanka,Ranbanka,0,2015,98,Action,3.7,118,Rahul an engineer tries his best to protect ...,A non-violent engineer resorts to violence aft...,A Film By Aryeman,Manish Paul|Ravi Kishan|Pooja Thakur|Rudra Kau...,1 win,6 November 2015 (India)
535,Desi Kattey,tt3877652,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Desi_Kattey,Desi Kattey,Desi Kattey,0,2014,139,Action,4.2,111,A sharpshooting thug becomes a competitive sho...,A sharpshooting thug becomes a competitive sho...,NaN,Sasha Aagha|Tia Bajpai|Rajesh Bakshi|Jay Bhanu...,1 nomination,12 September 2014 (India)
538,Spark (2014 film),tt3893476,NaN,https://en.wikipedia.org/wiki/Spark_(2014_film),Spark,Spark,0,2014,134,Action,5.7,28,The story is about a local Indian lad Arjun (R...,The story is about a local Indian lad Arjun (R...,NaN,Rati Agnihotri|Mansha Bahl|Rajniesh Duggall|Su...,NaN,10 October 2014 (India)
637,Boss (2013 Hindi film),tt2571140,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Boss_(2013_Hindi...,Boss,Boss,0,2013,143,Action,5.1,9674,Boss (Akshay Kumar) takes the blame for a murd...,A man fights for people's rights. In Delhi he...,The BOSS is here.,Akshay Kumar|Shiv Panditt|Mithun Chakraborty|R...,NaN,16 October 2013 (India)
1146,Adharm (2006 film),tt2435680,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Adharm_(2006_film),Adharm,Adharm,0,2006,\N,Action,5.1,7,This story is inspired by true incident that h...,This story is inspired by true incident that h...,NaN,Rahul Dev|Mayuri Kango|Rocky Khanna|Anupam Khe...,NaN,NaN
1171,Dharti Kahe Pukar Ke (2006 film),tt5216486,https://upload.wikimedia.org/wikipedia/en/6/64...,https://en.wikipedia.org/wiki/Dharti_Kahe_Puka...,Dharti Kahe Pukar Ke,Dharti Kahe Pukar Ke,0,2006,\N,Action,6.3,7,NaN,Add a Plot »,NaN,Ajay Devgn|Sharbani Mukherjee|,NaN,NaN
1310,Vidyaarthi,tt1483815,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vidyaarthi,Vidhyaarthi: The Power of Students,Vidhyaarthi: The Power of Students,0,2006,250,Action,5.0,8,This story about underworld and crime. How can...,This story about underworld and crime. How can...,The power of students,Vikram Aditya|Akash Ajmera|Ishrat Ali|Rajesh B...,NaN,18 June 2006 (India)
1411,Aaj Ka Andha Kanoon,tt0426863,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aaj_Ka_Andha_Kanoon,Aaj Ka Andha Kanoon,Aaj Ka Andha Kanoon,0,2003,46,Action,3.3,14,Deva comes to the city in search of work! He m...,Deva comes to the city in search of work! He m...,NaN,Sudesh Berry|Priyanka Upendra|Aman Jalali|Vish...,NaN,10 June 2003 (India)
1585,Bhairav (film),tt0466208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhairav_(film),Bhairav,Bhairav,0,2001,133,Action,5.0,23,Rakesh Pandey belongs to a middle-class family...,Rakesh Pandey belongs to a middle-class family...,NaN,Hemant Birje|Mithun Chakraborty|Jack Gaud|Brij...,NaN,2001 (India)
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)

In [ ]:
# Adding new colns 
#completly New

movie['Country']='India'
movie

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),India
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India),India
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India),India
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN,India
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA),India
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012),India

In [185]:
#dropping all missing values 
movie.info()
# movie.dropna(inplace=True)
movie.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB

In [190]:
#important  dataFrrame function 
#astype
Ipl_match.info()
Ipl_match['ID']=Ipl_match['ID'].astype('int32')
Ipl_match

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int32(1), str(18)
memory usage: 144.9 KB

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen